version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/dockerfiles/web-base/virtualenvs/biom"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/dockerfiles/web-base/virtualenvs/panimg"
    schedule:
      interval: "weekly"
    versioning-strategy: lockfile-only
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns:
          - "*"
