# Generated by Django 5.2.17 on 2026-09-23 13:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0104_alter_job_algorithm_interface"),
        ("archives", "0026_archive_archives_archive_unique_slug"),
        (
            "challenges",
            "0080_alter_challengerequest_average_size_test_case_mb_for_tasks_and_more",
        ),
        ("evaluation", "0112_phase_use_batch_mode_and_more"),
        ("invoices", "0021_auto_20260609_0849"),
        (
            "utilization",
            "0008_evaluationutilization_invoice_jobutilization_invoice_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchJobUtilization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("duration", models.DurationField(null=True)),
                (
                    "compute_cost_euro_millicents",
                    models.PositiveIntegerField(null=True),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "algorithm_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="algorithms.algorithmimage",
                    ),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archives.archive",
                    ),
                ),
                (
                    "batch_job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_job_utilization",
                        to="evaluation.batchjob",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.challenge",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="invoices.invoice",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluation.phase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "batch_job_utilizations",
                "indexes": [
                    models.Index(
                        fields=["-created"],
                        name="utilization_created_adde16_idx",
                    ),
                    models.Index(
                        fields=["phase", "duration"],
                        name="utilization_phase_i_bfd378_idx",
                    ),
                ],
            },
        ),
    ]
