# Generated by Django 5.2.17 on 2026-09-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0103_algorithm_algorithms_algorithm_unique_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="algorithm_interface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="algorithms.algorithminterface",
            ),
        ),
    ]
